### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Piersac** [cerberusServers/TranquilizerGun#3]
Hello, why when I try to give myself a tranquilizer then I write Permission denied?
I did everything as it was written in the Readme
My discord: Pozetiv4ik#6272

**Comment by ImBeryl** [comment]
Most likely an Exiled issue, you can read my message on the [Exiled FAQ](https://discordapp.com/channels/656673194693885975/656698014991384586/710562216361066588) to see how you can fix it. If you need any more help with issues related to Exiled you can also try the "support" Discord tab on the official Exiled Discord.
