### ISSUE TITLE
Problem with permissions

### ISSUE THREAD

**Issue by CPepperoni** [cerberusServers/TranquilizerGun#6]
So, gonna be quick, i am new to plugins so excuse me if this whole issue is a mistake of mine.

I'm trying to use the tranq gun plugin but i can't do anything since the "tg toggle" command doesn't work even when i changed the config.yml file it keeps saying the same.

I have to repeat, i'm new so this might be a rookie mistake but i really need help.

**Comment by SrLicht** [comment]
I am closing this because you have probably already found the solution, if not, reopen one and I will answer it myself.
